metrics:
  - type: fid
    model:
      dims: 2048
    data:
      dataset:
        resize_shape: [256, 512]
      batch_size: 16
      num_workers: 1

  - type: fvd
    model:
      # type: videogpt
      # path: i3d_pretrained_400.pt
      type: styleganv
      path: i3d_torchscript.pt
    data:
      dataset:
        sequence_length: 16
        resize_shape: [224, 224]
      batch_size: 4
      num_workers: 1

# num_iters: 1000
paths: [/home/numbnut/repo/Vidar_eval/fid-metrics/real_video/cam_high.mp4,/home/numbnut/repo/Vidar_eval/fid-metrics/gen_video/23972.mp4]
