# import packages and module here
import numpy as np
import cv2
from .vidar import Vidar # Import the Vidar class
from .vidar import SINGLE_ARM_DICT

def encode_obs(observation):  # Post-Process Observation
    obs = observation

    print("observation keys:", obs.keys())
    head_rgbs = np.array(obs['observation']["head_camera"]["rgb"])
    left_rgbs = np.array(obs['observation']["left_camera"]["rgb"])
    right_rgbs = np.array(obs['observation']["right_camera"]["rgb"])

    # rgb to bgr
    head_rgbs = head_rgbs[..., ::-1]
    left_rgbs = left_rgbs[..., ::-1]
    right_rgbs = right_rgbs[..., ::-1]
        
    # This logic assumes a single frame observation, not a sequence.
    # The original logic seemed to expect a sequence (len(head_rgbs)).
    # We'll process a single frame observation dict.
    head_img = head_rgbs
    left_img = left_rgbs
    right_img = right_rgbs
    
    h, w, _ = head_img.shape
    new_h, new_w = h // 2, w // 2
    
    left_resized = cv2.resize(left_img, (new_w, new_h), interpolation=cv2.INTER_AREA)
    right_resized = cv2.resize(right_img, (new_w, new_h), interpolation=cv2.INTER_AREA)
    
    bottom_row = np.concatenate([left_resized, right_resized], axis=1)
    
    if bottom_row.shape[1] != w:
        bottom_row = cv2.resize(bottom_row, (w, new_h), interpolation=cv2.INTER_AREA)
    
    final_h = h + new_h
    combined_img = np.zeros((final_h, w, 3), dtype=head_img.dtype)
    
    combined_img[:h, :w] = head_img
    combined_img[h:, :w] = bottom_row
    return combined_img


def get_model(usr_args):  # from deploy_policy.yml and eval.sh (overrides)
    """Initializes and returns the Vidar policy model."""
    model = Vidar(usr_args=usr_args)
    return model


def eval(TASK_ENV, model, observation):
    """
    The Vidar model now handles the full observation-to-action pipeline.
    """
    obs = encode_obs(observation)
    instruction = TASK_ENV.get_instruction()

    # Set instruction and update observation for the model

    # Set task name
    model.set_task_name(TASK_ENV.task_name)

    if TASK_ENV.task_name in SINGLE_ARM_DICT:
        model.set_arm_tag(TASK_ENV.arm_tag)
    model.set_episode_id(TASK_ENV.ep_num)
    model.set_instruction(instruction)
    model.update_obs(obs)

    # Vidar model now directly returns a sequence of actions
    actions = model.get_action()
    
    # --- Action Execution Loop ---
    print(f"Executing {len(actions)} actions generated by Vidar...")
    for action in actions:
        # Execute each step of the action
        TASK_ENV.take_action(action, action_type='qpos')
        # We don't get new observations inside the loop as this is an open-loop execution
        # based on the initial observation.

    print("Finished executing Vidar-generated actions.")


def reset_model(model):  
    """Cleans the model cache at the beginning of every evaluation episode."""
    model.reset()
